name: SpyerAdmin

main: nickguletskii200.Spyer

version: 0.3_3

commands:
  spy:
    description: Hides the player until used again
    usage: /spy
  quit:
    description: Hides the player until used again, simulates quitting
    usage: /quit