# System is no longer used, but may become used in the future
# Copies is for multiple-world support
#   Put the name of the world you wish for it to be a clone of, otherwise leave it empty.
#   Does not work for the default world.
#  Example: copies: Derp    -  This will clone the permissions of the world Derp
#
# Make sure to rename this file to the name of the world that is in sever.properties under
# level-name.  So if it is level-name: world  then this should be world.yml and in the 
# plugins/Permissions directory (ie. plugins/Permissions/world.yml)
#
# NOTE: Do not use tabs while editing this document.  Use only spaces.  A good way to avoid
# doing this is to use Notepad++ and replace the tab with 4 spaces.
plugin:
    permissions:
        system: default
        copies: 

##        
# AntiBuild is included with this.  To disable a group from being able to build then
# set the build: flag to false (build: false).  If you want a group to be able to build
# then set it to true. 
##
# Groups can contain inheritance.
#   To make a group inherit the permissions from another
#   group simply place the groups name in the "inheritance:" like so:
#
#   Example:
#       inheritance:
#           - Default
##
#   All permissions including the asterisks must be placed in single quotes.
#   like so:
#
#       - 'general.spawn'
#
#   Otherwise errors will happen!
##
#   Globalized Permission settings:
#
#       If a permission contains periods (.) you can denote a globalized parameter:
#
#           - 'general.*'
#
#       This will allow you to use all general commands.
#
##
#   Single Asterisk denotes all commands:
#
#       - '*'
#   If you give a group this permissions, do not have the group inherit any permissions
#   from other groups.  Any users assigned to this group should NOT be given any additional
#   permissions either.
##
#   To exempt a node use the - prefix like so:
#       - '-general.time'
##
#   prefix: and suffix: do not do anything on their own.  You need another outside plugin
#   such as iChat or HeroChat in order for these to do anything.
groups:
    Default:
        default: true
        info:
            prefix: 'asd'
            suffix: ''
            build: false
        inheritance:
        permissions:
            - 'nil'
    Moderator:
        default: false
        info:
            prefix: ''
            suffix: ''
            build: true
        inheritance:
            - Default
        permissions:
            - 'bar.foo'
    Admins:
        default: false
        info:
            prefix: ':P'
            suffix: ''
            build: true
        inheritance:
        permissions:
            - '*'

##
# Users denote which users are included in which group.
# Users can also have a prefix and suffix as seen with Herpina
##
users:

    # TheNo1Yeti is in the Admin group
    nickguletskii200:
        group: Admins
        permissions:

    # Herpina is a member of the Moderator group but also has access to the herp.derp permissions
    Herpina:
        group: Moderator
        info:
            prefix: 'Moo'
            suffix: 'Cow'
        permissions:
            - 'herp.derp'

    # Derpina is a member of the admin group but does not have access to the derp.derp permission node
    Derpina:
        group: Admins
        permissions:
            - '-derp.derp'